// Code generated by MockGen. DO NOT EDIT.
// Package managermock is a generated GoMock package.
package managermock

import (
	"reflect"

	"github.com/luxfi/ids"
	"github.com/luxfi/log"
	"go.uber.org/mock/gomock"
)

// Factory is a mock of Factory interface.
type Factory struct {
	ctrl     *gomock.Controller
	recorder *FactoryMockRecorder
}

// FactoryMockRecorder is the mock recorder for Factory.
type FactoryMockRecorder struct {
	mock *Factory
}

// NewFactory creates a new mock instance.
func NewFactory(ctrl *gomock.Controller) *Factory {
	mock := &Factory{ctrl: ctrl}
	mock.recorder = &FactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Factory) EXPECT() *FactoryMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *Factory) New(arg0 log.Logger) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", arg0)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *FactoryMockRecorder) New(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*Factory)(nil).New), arg0)
}

// Manager is a mock of Manager interface.
type Manager struct {
	ctrl     *gomock.Controller
	recorder *ManagerMockRecorder
}

// ManagerMockRecorder is the mock recorder for Manager.
type ManagerMockRecorder struct {
	mock *Manager
}

// NewManager creates a new mock instance.
func NewManager(ctrl *gomock.Controller) *Manager {
	mock := &Manager{ctrl: ctrl}
	mock.recorder = &ManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Manager) EXPECT() *ManagerMockRecorder {
	return m.recorder
}

// GetFactory mocks base method.
func (m *Manager) GetFactory(arg0 ids.ID) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFactory", arg0)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFactory indicates an expected call of GetFactory.
func (mr *ManagerMockRecorder) GetFactory(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFactory", reflect.TypeOf((*Manager)(nil).GetFactory), arg0)
}

// RegisterFactory mocks base method.
func (m *Manager) RegisterFactory(arg0 ids.ID, arg1 any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterFactory", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterFactory indicates an expected call of RegisterFactory.
func (mr *ManagerMockRecorder) RegisterFactory(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterFactory", reflect.TypeOf((*Manager)(nil).RegisterFactory), arg0, arg1)
}

// ListFactories mocks base method.
func (m *Manager) ListFactories() ([]ids.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFactories")
	ret0, _ := ret[0].([]ids.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFactories indicates an expected call of ListFactories.
func (mr *ManagerMockRecorder) ListFactories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFactories", reflect.TypeOf((*Manager)(nil).ListFactories))
}

// Versions mocks base method.
func (m *Manager) Versions() (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Versions")
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Versions indicates an expected call of Versions.
func (mr *ManagerMockRecorder) Versions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Versions", reflect.TypeOf((*Manager)(nil).Versions))
}
