// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: dag/dag.proto

package dag

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DAGVM_Initialize_FullMethodName       = "/dag.DAGVM/Initialize"
	DAGVM_SetState_FullMethodName         = "/dag.DAGVM/SetState"
	DAGVM_Shutdown_FullMethodName         = "/dag.DAGVM/Shutdown"
	DAGVM_CreateHandlers_FullMethodName   = "/dag.DAGVM/CreateHandlers"
	DAGVM_WaitForEvent_FullMethodName     = "/dag.DAGVM/WaitForEvent"
	DAGVM_Connected_FullMethodName        = "/dag.DAGVM/Connected"
	DAGVM_Disconnected_FullMethodName     = "/dag.DAGVM/Disconnected"
	DAGVM_BuildVertex_FullMethodName      = "/dag.DAGVM/BuildVertex"
	DAGVM_ParseVertex_FullMethodName      = "/dag.DAGVM/ParseVertex"
	DAGVM_GetVertex_FullMethodName        = "/dag.DAGVM/GetVertex"
	DAGVM_SetPreference_FullMethodName    = "/dag.DAGVM/SetPreference"
	DAGVM_LastAccepted_FullMethodName     = "/dag.DAGVM/LastAccepted"
	DAGVM_Health_FullMethodName           = "/dag.DAGVM/Health"
	DAGVM_Version_FullMethodName          = "/dag.DAGVM/Version"
	DAGVM_AppRequest_FullMethodName       = "/dag.DAGVM/AppRequest"
	DAGVM_AppRequestFailed_FullMethodName = "/dag.DAGVM/AppRequestFailed"
	DAGVM_AppResponse_FullMethodName      = "/dag.DAGVM/AppResponse"
	DAGVM_AppGossip_FullMethodName        = "/dag.DAGVM/AppGossip"
	DAGVM_Gather_FullMethodName           = "/dag.DAGVM/Gather"
	DAGVM_VertexVerify_FullMethodName     = "/dag.DAGVM/VertexVerify"
	DAGVM_VertexAccept_FullMethodName     = "/dag.DAGVM/VertexAccept"
	DAGVM_VertexReject_FullMethodName     = "/dag.DAGVM/VertexReject"
)

// DAGVMClient is the client API for DAGVM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DAGVMClient interface {
	// Initialize this DAG VM.
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	// SetState communicates to VM its next state it starts
	SetState(ctx context.Context, in *SetStateRequest, opts ...grpc.CallOption) (*SetStateResponse, error)
	// Shutdown is called when the node is shutting down.
	Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Creates the HTTP handlers for custom network calls.
	CreateHandlers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CreateHandlersResponse, error)
	// WaitForEvent blocks until receiving the next event from the VM.
	WaitForEvent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*WaitForEventResponse, error)
	Connected(ctx context.Context, in *ConnectedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Disconnected(ctx context.Context, in *DisconnectedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Vertex operations (DAG-specific)
	// Attempt to create a new vertex from data contained in the VM.
	BuildVertex(ctx context.Context, in *BuildVertexRequest, opts ...grpc.CallOption) (*BuildVertexResponse, error)
	// Attempt to parse a vertex from bytes.
	ParseVertex(ctx context.Context, in *ParseVertexRequest, opts ...grpc.CallOption) (*ParseVertexResponse, error)
	// Attempt to load a vertex by ID.
	GetVertex(ctx context.Context, in *GetVertexRequest, opts ...grpc.CallOption) (*GetVertexResponse, error)
	// Notify the VM of the currently preferred vertex.
	SetPreference(ctx context.Context, in *SetPreferenceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get the last accepted vertex ID.
	LastAccepted(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LastAcceptedResponse, error)
	// Health and version
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
	// App messaging
	AppRequest(ctx context.Context, in *AppRequestMsg, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AppRequestFailed(ctx context.Context, in *AppRequestFailedMsg, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AppResponse(ctx context.Context, in *AppResponseMsg, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AppGossip(ctx context.Context, in *AppGossipMsg, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Metrics
	Gather(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GatherResponse, error)
	// Vertex lifecycle
	VertexVerify(ctx context.Context, in *VertexVerifyRequest, opts ...grpc.CallOption) (*VertexVerifyResponse, error)
	VertexAccept(ctx context.Context, in *VertexAcceptRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	VertexReject(ctx context.Context, in *VertexRejectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type dAGVMClient struct {
	cc grpc.ClientConnInterface
}

func NewDAGVMClient(cc grpc.ClientConnInterface) DAGVMClient {
	return &dAGVMClient{cc}
}

func (c *dAGVMClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, DAGVM_Initialize_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) SetState(ctx context.Context, in *SetStateRequest, opts ...grpc.CallOption) (*SetStateResponse, error) {
	out := new(SetStateResponse)
	err := c.cc.Invoke(ctx, DAGVM_SetState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DAGVM_Shutdown_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) CreateHandlers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CreateHandlersResponse, error) {
	out := new(CreateHandlersResponse)
	err := c.cc.Invoke(ctx, DAGVM_CreateHandlers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) WaitForEvent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*WaitForEventResponse, error) {
	out := new(WaitForEventResponse)
	err := c.cc.Invoke(ctx, DAGVM_WaitForEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) Connected(ctx context.Context, in *ConnectedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DAGVM_Connected_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) Disconnected(ctx context.Context, in *DisconnectedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DAGVM_Disconnected_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) BuildVertex(ctx context.Context, in *BuildVertexRequest, opts ...grpc.CallOption) (*BuildVertexResponse, error) {
	out := new(BuildVertexResponse)
	err := c.cc.Invoke(ctx, DAGVM_BuildVertex_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) ParseVertex(ctx context.Context, in *ParseVertexRequest, opts ...grpc.CallOption) (*ParseVertexResponse, error) {
	out := new(ParseVertexResponse)
	err := c.cc.Invoke(ctx, DAGVM_ParseVertex_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) GetVertex(ctx context.Context, in *GetVertexRequest, opts ...grpc.CallOption) (*GetVertexResponse, error) {
	out := new(GetVertexResponse)
	err := c.cc.Invoke(ctx, DAGVM_GetVertex_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) SetPreference(ctx context.Context, in *SetPreferenceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DAGVM_SetPreference_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) LastAccepted(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LastAcceptedResponse, error) {
	out := new(LastAcceptedResponse)
	err := c.cc.Invoke(ctx, DAGVM_LastAccepted_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DAGVM_Health_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, DAGVM_Version_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) AppRequest(ctx context.Context, in *AppRequestMsg, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DAGVM_AppRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) AppRequestFailed(ctx context.Context, in *AppRequestFailedMsg, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DAGVM_AppRequestFailed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) AppResponse(ctx context.Context, in *AppResponseMsg, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DAGVM_AppResponse_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) AppGossip(ctx context.Context, in *AppGossipMsg, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DAGVM_AppGossip_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) Gather(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GatherResponse, error) {
	out := new(GatherResponse)
	err := c.cc.Invoke(ctx, DAGVM_Gather_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) VertexVerify(ctx context.Context, in *VertexVerifyRequest, opts ...grpc.CallOption) (*VertexVerifyResponse, error) {
	out := new(VertexVerifyResponse)
	err := c.cc.Invoke(ctx, DAGVM_VertexVerify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) VertexAccept(ctx context.Context, in *VertexAcceptRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DAGVM_VertexAccept_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGVMClient) VertexReject(ctx context.Context, in *VertexRejectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DAGVM_VertexReject_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DAGVMServer is the server API for DAGVM service.
// All implementations must embed UnimplementedDAGVMServer
// for forward compatibility
type DAGVMServer interface {
	// Initialize this DAG VM.
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	// SetState communicates to VM its next state it starts
	SetState(context.Context, *SetStateRequest) (*SetStateResponse, error)
	// Shutdown is called when the node is shutting down.
	Shutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Creates the HTTP handlers for custom network calls.
	CreateHandlers(context.Context, *emptypb.Empty) (*CreateHandlersResponse, error)
	// WaitForEvent blocks until receiving the next event from the VM.
	WaitForEvent(context.Context, *emptypb.Empty) (*WaitForEventResponse, error)
	Connected(context.Context, *ConnectedRequest) (*emptypb.Empty, error)
	Disconnected(context.Context, *DisconnectedRequest) (*emptypb.Empty, error)
	// Vertex operations (DAG-specific)
	// Attempt to create a new vertex from data contained in the VM.
	BuildVertex(context.Context, *BuildVertexRequest) (*BuildVertexResponse, error)
	// Attempt to parse a vertex from bytes.
	ParseVertex(context.Context, *ParseVertexRequest) (*ParseVertexResponse, error)
	// Attempt to load a vertex by ID.
	GetVertex(context.Context, *GetVertexRequest) (*GetVertexResponse, error)
	// Notify the VM of the currently preferred vertex.
	SetPreference(context.Context, *SetPreferenceRequest) (*emptypb.Empty, error)
	// Get the last accepted vertex ID.
	LastAccepted(context.Context, *emptypb.Empty) (*LastAcceptedResponse, error)
	// Health and version
	Health(context.Context, *emptypb.Empty) (*HealthResponse, error)
	Version(context.Context, *emptypb.Empty) (*VersionResponse, error)
	// App messaging
	AppRequest(context.Context, *AppRequestMsg) (*emptypb.Empty, error)
	AppRequestFailed(context.Context, *AppRequestFailedMsg) (*emptypb.Empty, error)
	AppResponse(context.Context, *AppResponseMsg) (*emptypb.Empty, error)
	AppGossip(context.Context, *AppGossipMsg) (*emptypb.Empty, error)
	// Metrics
	Gather(context.Context, *emptypb.Empty) (*GatherResponse, error)
	// Vertex lifecycle
	VertexVerify(context.Context, *VertexVerifyRequest) (*VertexVerifyResponse, error)
	VertexAccept(context.Context, *VertexAcceptRequest) (*emptypb.Empty, error)
	VertexReject(context.Context, *VertexRejectRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedDAGVMServer()
}

// UnimplementedDAGVMServer must be embedded to have forward compatible implementations.
type UnimplementedDAGVMServer struct {
}

func (UnimplementedDAGVMServer) Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedDAGVMServer) SetState(context.Context, *SetStateRequest) (*SetStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetState not implemented")
}
func (UnimplementedDAGVMServer) Shutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedDAGVMServer) CreateHandlers(context.Context, *emptypb.Empty) (*CreateHandlersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHandlers not implemented")
}
func (UnimplementedDAGVMServer) WaitForEvent(context.Context, *emptypb.Empty) (*WaitForEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitForEvent not implemented")
}
func (UnimplementedDAGVMServer) Connected(context.Context, *ConnectedRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connected not implemented")
}
func (UnimplementedDAGVMServer) Disconnected(context.Context, *DisconnectedRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnected not implemented")
}
func (UnimplementedDAGVMServer) BuildVertex(context.Context, *BuildVertexRequest) (*BuildVertexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildVertex not implemented")
}
func (UnimplementedDAGVMServer) ParseVertex(context.Context, *ParseVertexRequest) (*ParseVertexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseVertex not implemented")
}
func (UnimplementedDAGVMServer) GetVertex(context.Context, *GetVertexRequest) (*GetVertexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVertex not implemented")
}
func (UnimplementedDAGVMServer) SetPreference(context.Context, *SetPreferenceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPreference not implemented")
}
func (UnimplementedDAGVMServer) LastAccepted(context.Context, *emptypb.Empty) (*LastAcceptedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastAccepted not implemented")
}
func (UnimplementedDAGVMServer) Health(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedDAGVMServer) Version(context.Context, *emptypb.Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedDAGVMServer) AppRequest(context.Context, *AppRequestMsg) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppRequest not implemented")
}
func (UnimplementedDAGVMServer) AppRequestFailed(context.Context, *AppRequestFailedMsg) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppRequestFailed not implemented")
}
func (UnimplementedDAGVMServer) AppResponse(context.Context, *AppResponseMsg) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppResponse not implemented")
}
func (UnimplementedDAGVMServer) AppGossip(context.Context, *AppGossipMsg) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppGossip not implemented")
}
func (UnimplementedDAGVMServer) Gather(context.Context, *emptypb.Empty) (*GatherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Gather not implemented")
}
func (UnimplementedDAGVMServer) VertexVerify(context.Context, *VertexVerifyRequest) (*VertexVerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VertexVerify not implemented")
}
func (UnimplementedDAGVMServer) VertexAccept(context.Context, *VertexAcceptRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VertexAccept not implemented")
}
func (UnimplementedDAGVMServer) VertexReject(context.Context, *VertexRejectRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VertexReject not implemented")
}
func (UnimplementedDAGVMServer) mustEmbedUnimplementedDAGVMServer() {}

// UnsafeDAGVMServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DAGVMServer will
// result in compilation errors.
type UnsafeDAGVMServer interface {
	mustEmbedUnimplementedDAGVMServer()
}

func RegisterDAGVMServer(s grpc.ServiceRegistrar, srv DAGVMServer) {
	s.RegisterService(&DAGVM_ServiceDesc, srv)
}

func _DAGVM_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_SetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).SetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_SetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).SetState(ctx, req.(*SetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).Shutdown(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_CreateHandlers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).CreateHandlers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_CreateHandlers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).CreateHandlers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_WaitForEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).WaitForEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_WaitForEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).WaitForEvent(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_Connected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).Connected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_Connected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).Connected(ctx, req.(*ConnectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_Disconnected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).Disconnected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_Disconnected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).Disconnected(ctx, req.(*DisconnectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_BuildVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildVertexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).BuildVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_BuildVertex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).BuildVertex(ctx, req.(*BuildVertexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_ParseVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseVertexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).ParseVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_ParseVertex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).ParseVertex(ctx, req.(*ParseVertexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_GetVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVertexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).GetVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_GetVertex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).GetVertex(ctx, req.(*GetVertexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_SetPreference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPreferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).SetPreference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_SetPreference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).SetPreference(ctx, req.(*SetPreferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_LastAccepted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).LastAccepted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_LastAccepted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).LastAccepted(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).Version(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_AppRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).AppRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_AppRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).AppRequest(ctx, req.(*AppRequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_AppRequestFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequestFailedMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).AppRequestFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_AppRequestFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).AppRequestFailed(ctx, req.(*AppRequestFailedMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_AppResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppResponseMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).AppResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_AppResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).AppResponse(ctx, req.(*AppResponseMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_AppGossip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppGossipMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).AppGossip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_AppGossip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).AppGossip(ctx, req.(*AppGossipMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_Gather_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).Gather(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_Gather_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).Gather(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_VertexVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VertexVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).VertexVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_VertexVerify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).VertexVerify(ctx, req.(*VertexVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_VertexAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VertexAcceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).VertexAccept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_VertexAccept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).VertexAccept(ctx, req.(*VertexAcceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGVM_VertexReject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VertexRejectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGVMServer).VertexReject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGVM_VertexReject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGVMServer).VertexReject(ctx, req.(*VertexRejectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DAGVM_ServiceDesc is the grpc.ServiceDesc for DAGVM service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DAGVM_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dag.DAGVM",
	HandlerType: (*DAGVMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _DAGVM_Initialize_Handler,
		},
		{
			MethodName: "SetState",
			Handler:    _DAGVM_SetState_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _DAGVM_Shutdown_Handler,
		},
		{
			MethodName: "CreateHandlers",
			Handler:    _DAGVM_CreateHandlers_Handler,
		},
		{
			MethodName: "WaitForEvent",
			Handler:    _DAGVM_WaitForEvent_Handler,
		},
		{
			MethodName: "Connected",
			Handler:    _DAGVM_Connected_Handler,
		},
		{
			MethodName: "Disconnected",
			Handler:    _DAGVM_Disconnected_Handler,
		},
		{
			MethodName: "BuildVertex",
			Handler:    _DAGVM_BuildVertex_Handler,
		},
		{
			MethodName: "ParseVertex",
			Handler:    _DAGVM_ParseVertex_Handler,
		},
		{
			MethodName: "GetVertex",
			Handler:    _DAGVM_GetVertex_Handler,
		},
		{
			MethodName: "SetPreference",
			Handler:    _DAGVM_SetPreference_Handler,
		},
		{
			MethodName: "LastAccepted",
			Handler:    _DAGVM_LastAccepted_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _DAGVM_Health_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _DAGVM_Version_Handler,
		},
		{
			MethodName: "AppRequest",
			Handler:    _DAGVM_AppRequest_Handler,
		},
		{
			MethodName: "AppRequestFailed",
			Handler:    _DAGVM_AppRequestFailed_Handler,
		},
		{
			MethodName: "AppResponse",
			Handler:    _DAGVM_AppResponse_Handler,
		},
		{
			MethodName: "AppGossip",
			Handler:    _DAGVM_AppGossip_Handler,
		},
		{
			MethodName: "Gather",
			Handler:    _DAGVM_Gather_Handler,
		},
		{
			MethodName: "VertexVerify",
			Handler:    _DAGVM_VertexVerify_Handler,
		},
		{
			MethodName: "VertexAccept",
			Handler:    _DAGVM_VertexAccept_Handler,
		},
		{
			MethodName: "VertexReject",
			Handler:    _DAGVM_VertexReject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dag/dag.proto",
}
